imports:
    - { resource: "@AppBundle/Resources/config/services_core_controllers.yml" }

parameters:
    app.abstract_manager.class: AppBundle\Services\Manager\AbstractManager
    app.parameters_calls.class: AppBundle\Services\Manager\ParametersManager
    app.factory.abstract.class: AppBundle\Factory\AbstractFactory

    app.user_manager.class:  AppBundle\Services\Manager\UserManager
    app.entity.user_manager.class:  AppBundle\Entity\User
    app.entityname.user_manager.class: 'AppBundle\Entity\User'
    app.argname.user_manager.class: 'Le User'

services:
    app.parameters_calls:
        class: '%app.parameters_calls.class%'
        arguments: ['@doctrine']

    app.abstract_manager:
        class: '%app.abstract_manager.class%'
        abstract: true
        arguments: ['@doctrine', '@session']

    app.factory.abstract:
        class: '%app.factory.abstract.class%'
        abstract: true

    twig.extension.intl:
           class: Twig_Extensions_Extension_Intl
           tags:
               - { name: twig.extension }

    app.user_manager:
        class: '%app.user_manager.class%'
        parent: app.abstract_manager
        calls:
        - [setEntity, ["%app.entity.user_manager.class%"]]
        - [setEntityName, ["%app.entityname.user_manager.class%"]]
        - [setArgname, ["%app.argname.user_manager.class%"]]